baseURL = "https://naughty-visvesvaraya-ec04e9.netlify.app/"
languageCode = "en-us"
title = "Gudbev's Sparkling Reviews"
theme = "base"

[taxonomies]
  tag="tags"
  category="categories"
  brand="brands"
  flavor="flavors"
  award="awards"
  neutral="neutrals"
  warning="warnings"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "."
  title = "Gudbev's Sparkling Reviews"
  headerImage  = "images/header.png"
  author = "Tough Pixels"
  imageSizes = "1280 840 360"
  imageFormats = "webp jpg"