baseURL = "https://stupefied-kare-38904c.netlify.app/"
languageCode = "en-us"
title = "Gudbev's Sparkling Reviews"
theme = "base"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
