baseURL = "https://gudbevs.netlify.app/"
languageCode = "en-us"
title = "Gudbev's Sparkling Reviews"
theme = "base"
description = "Explore our wide selection of sparking beverage reviews. Sparkling water is our passion, so enjoy these thirst quenching thoughts."

[taxonomies]
  brand="brands"
  flavor="flavors"
  rating="rating"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "."
  author = "Tough Pixels"
  imageSizes = "1280 768 320"
  imageFormats = "webp jpg"
