baseURL = "https://naughty-visvesvaraya-ec04e9.netlify.app/"
languageCode = "en-us"
title = "Gudbev's Sparkling Reviews"
theme = "base"

[taxonomies]
  tag="tags"
  category="categories"
  brand="brands"
  flavor="flavors"
  good="goods"
  medium="mediums"
  bad="bads"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "."
  title = "Gudbev's Sparkling Reviews"
  author = "Tough Pixels"
  imageSizes = "1280 768 320"
  imageFormats = "webp jpg"
