backend:
  name: git-gateway
  branch: main
  local_backend: true
media_folder: assets/img
public_folder: /img
collections:
  - name: 'reviews'
    label: 'Reviews'
    folder: 'content/reviews/{{year}}_{{month}}_{{day}}_{{title}}/'
    create: true
    slug: 'index.html'
    media_folder: ''
    editor:
      preview: false
    fields:
      - { label: 'Brand', name: 'brand', widget: 'string' }
      - { label: 'Flavors', name: 'flavors', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Rating', name: 'rating', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image'}
      - { label: 'The Good', name: 'goods', widget: 'string' }
      - { label: 'The Medium', name: 'mediums', widget: 'string' }
      - { label: 'The Bad', name: 'bads', widget: 'string' }
      - { label: "Your Review:", name: "body", widget: "markdown"}
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }