backend:
  name: git-gateway
  branch: main
  local_backend: true
media_folder: assets/img
public_folder: /img
collections:
  - name: 'reviews'
    label: 'Reviews'
    folder: 'content/reviews'
    path: '{{slug}}/index'
    create: true
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - { label: 'List', name: 'list', widget: 'list' }
      - { label: 'Brand', name: 'brand', widget: 'string' }
      - { label: 'Flavors', name: 'flavors', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Rating', name: 'rating', widget: 'number', min: 0, max: 10, step: 0.1 }
      - { label: 'Image', name: 'image', widget: 'image', choose_url: false }
      - { label: "Your Review:", name: "body", widget: "markdown" }
      - { label: 'The Good', name: 'goods', widget: 'string', required: false }
      - { label: 'The Medium', name: 'mediums', widget: 'string', required: false }
      - { label: 'The Bad', name: 'bads', widget: 'string', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }