backend:
  name: git-gateway
  branch: main
media_folder: assets/img
public_folder: /img
collections:
  - name: 'pages'
    label: 'Pages'
    create: true
    fields:
      - {
              label: 'Description',
              name: 'description',
              widget: 'string',
              hint: 'A single sentence description of what the page is about',
              required: false
      }
      - { label: 'Body', name: 'body', widget: 'markdown' }
            
            
            
  - name: 'sections'
    label: 'Homepage Sections'
    folder: 'content/home'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Short Title', name: 'title', widget: 'string', hint: 'This is what appears in the navigation bar.' }
      - { label: 'Long Title', name: 'title_long', widget: 'string' }
      - { label: 'Weight', name: 'weight', widget: 'number', value_type: 'int', hint: 'Sections with larger numbers will appear later.  Initially write these in increments of 10 so that it is easy to later move a section between two others.' }
      - { label: 'Image', name: 'image', widget: 'object', required: false, fields: [{ label: 'Image', name: 'image', widget: 'image', hint: 'This should be no more than 1200px wide.  Also please convert it to a webp format: https://convertio.co/jpg-webp/' }, { label: 'Image Alt', name: 'image_alt', widget: 'string', hint: "This is the description of the image for visually-impaired users" }]}
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'If you add any headers, make sure that they are an "H3" size.  If you want any sub-headers, use an "H4" size.  Want to center some text?  Copy and paste this: {{< center >}}✨✨✨✨{{< /center >}} and replace the stars with the text you want to center.' }
      